import { describe, it, expect, beforeEach, vi } from 'vitest'

/**
 * Loop prevention here is exactly one rule: a shroom does not act on a card it created.
 *
 * It was briefly written as "skip any card any shroom created", which made every
 * AI-generated card permanently inert — drag one into a watched column and nothing
 * happened, with no error and nothing in the shroom's history to explain it.
 */

const WATCHED_COLUMN = 'col-under-review'

const runs: string[] = []

vi.mock('@/lib/shrooms/runServerSide', () => ({
  runShroomServerSide: async ({ instruction }: { instruction: { id: string } }) => {
    runs.push(instruction.id)
    return { status: 'ran', cardsAffected: 1 }
  },
  rowToInstructionCard: (row: unknown) => row,
}))

const shroomRows = [
  {
    id: 'critique',
    isEnabled: true,
    triggers: [{ type: 'event', eventType: 'card_moved_to', columnId: WATCHED_COLUMN }],
  },
  {
    id: 'generator',
    isEnabled: true,
    triggers: [{ type: 'event', eventType: 'card_moved_to', columnId: WATCHED_COLUMN }],
  },
  {
    id: 'disabled-one',
    isEnabled: false,
    triggers: [{ type: 'event', eventType: 'card_moved_to', columnId: WATCHED_COLUMN }],
  },
  {
    id: 'watches-elsewhere',
    isEnabled: true,
    triggers: [{ type: 'event', eventType: 'card_moved_to', columnId: 'col-other' }],
  },
]

vi.mock('@/lib/db', () => ({
  db: {
    query: {
      instructionCards: {
        findMany: async () => shroomRows,
      },
    },
  },
}))

import { runEventTriggers } from '@/lib/shrooms/runEventTriggers'

const move = (createdByInstructionId?: string | null) =>
  runEventTriggers({
    channelId: 'chan1',
    columnId: WATCHED_COLUMN,
    eventType: 'card_moved_to',
    cardId: 'card1',
    createdByInstructionId,
  })

describe('event triggers', () => {
  beforeEach(() => {
    runs.length = 0
  })

  it('runs every enabled shroom watching the column', async () => {
    await move(null)
    expect(runs).toEqual(['critique', 'generator'])
  })

  it('still runs when the card was generated by a different shroom', async () => {
    // The reported bug: three cards made by a generate shroom, dragged into the column
    // its critique shroom watches, and nothing ran.
    await move('generator')
    expect(runs).toContain('critique')
  })

  it('never lets a shroom act on a card it created', async () => {
    await move('generator')
    expect(runs).not.toContain('generator')
  })

  it('ignores disabled shrooms and shrooms watching another column', async () => {
    await move(null)
    expect(runs).not.toContain('disabled-one')
    expect(runs).not.toContain('watches-elsewhere')
  })
})
