// Static seed data for the Kanthink Marketplace
// 20 Shrooms (AI automation templates) + 20 Channels (collaborative spaces)

export interface MarketplaceShroom {
  slug: string
  name: string
  tagline: string
  description: string
  category: string
  tags: string[]
  icon: string // emoji
  action: 'generate' | 'modify' | 'move'
  instructions: string
  usageCount: number
}

export interface MarketplaceChannel {
  slug: string
  name: string
  tagline: string
  description: string
  category: string
  tags: string[]
  icon: string // emoji
  columns: string[]
  aiInstructions: string
  usageCount: number
}

export const SHROOM_CATEGORIES = [
  'Productivity',
  'Engineering',
  'Design',
  'Marketing',
  'Personal',
  'Team',
] as const

export const CHANNEL_CATEGORIES = [
  'Team',
  'Community',
  'Personal',
  'Learning',
  'Creative',
  'Operations',
] as const

export const shrooms: MarketplaceShroom[] = [
  {
    slug: 'daily-standup',
    name: 'Daily Standup',
    tagline: 'Generate standup cards from yesterday\'s activity',
    description: 'Automatically creates standup cards each morning based on card movements from the previous day. Summarizes what was completed, what\'s in progress, and surfaces blockers. Drop this into any team channel to replace manual standup updates.',
    category: 'Team',
    tags: ['standup', 'agile', 'daily', 'team'],
    icon: '🌅',
    action: 'generate',
    instructions: 'Every morning, scan the channel for cards that moved yesterday. Generate a standup summary card with three sections: Done (cards moved to completed), In Progress (cards currently being worked on), and Blockers (cards that haven\'t moved in 3+ days).',
    usageCount: 2847,
  },
  {
    slug: 'bug-triage',
    name: 'Bug Triage',
    tagline: 'Auto-classify and prioritize incoming bugs',
    description: 'Analyzes new bug reports and automatically classifies them by severity (critical, high, medium, low) and area (frontend, backend, infra, UX). Moves cards to the appropriate priority column and adds structured tags. Works best with a channel that has severity-based columns.',
    category: 'Engineering',
    tags: ['bugs', 'triage', 'priority', 'engineering'],
    icon: '🐛',
    action: 'move',
    instructions: 'When a new card appears in the Inbox column, analyze its title and description. Classify by severity (P0-P3) and affected area. Add tags, set priority, and move to the appropriate column. P0/P1 → Urgent, P2 → This Week, P3 → Backlog.',
    usageCount: 1923,
  },
  {
    slug: 'weekly-planner',
    name: 'Weekly Planner',
    tagline: 'Plan your week with AI-suggested priorities',
    description: 'Every Monday morning, reviews your backlog and in-progress items, then generates a suggested weekly plan. Creates cards in your "This Week" column ranked by urgency, dependencies, and deadlines. Learns from your patterns over time.',
    category: 'Productivity',
    tags: ['planning', 'weekly', 'priorities', 'organization'],
    icon: '📅',
    action: 'generate',
    instructions: 'On Monday, review all cards across columns. Identify items by urgency and deadline. Generate a "Weekly Plan" card listing the top 5-7 items to focus on this week, with brief reasoning for each. Move suggested items to the "This Week" column.',
    usageCount: 3412,
  },
  {
    slug: 'sprint-retro',
    name: 'Sprint Retrospective',
    tagline: 'Generate retro insights from sprint activity',
    description: 'At the end of each sprint, analyzes all card movements, completion rates, and patterns to generate a retrospective summary. Highlights what went well, what could improve, and suggests action items for the next sprint.',
    category: 'Team',
    tags: ['retro', 'sprint', 'agile', 'reflection'],
    icon: '🔄',
    action: 'generate',
    instructions: 'Analyze all card activity from the past two weeks. Calculate completion rate, average time in each column, and identify bottlenecks. Generate a retro card with: What Went Well, What Could Improve, and Action Items sections.',
    usageCount: 1567,
  },
  {
    slug: 'content-calendar',
    name: 'Content Calendar',
    tagline: 'AI-generated content ideas on a schedule',
    description: 'Generates content ideas based on your brand voice, target audience, and content pillars. Creates cards with titles, hooks, key points, and suggested publish dates. Maintains variety across content types (blog, social, video, newsletter).',
    category: 'Marketing',
    tags: ['content', 'calendar', 'social', 'marketing'],
    icon: '📝',
    action: 'generate',
    instructions: 'Based on the channel\'s content pillars and target audience described in instructions, generate 5 content ideas per week. Each card should include: title, content type, hook/angle, 3 key points, and suggested publish date. Maintain variety across types.',
    usageCount: 2156,
  },
  {
    slug: 'onboarding-tracker',
    name: 'Onboarding Tracker',
    tagline: 'Structured onboarding checklists for new hires',
    description: 'Creates a complete onboarding checklist when a new team member joins. Generates cards for each onboarding step: accounts setup, tool access, team introductions, training sessions, and 30/60/90 day goals. Tracks progress as cards move through columns.',
    category: 'Team',
    tags: ['onboarding', 'hr', 'checklist', 'new-hire'],
    icon: '🎯',
    action: 'generate',
    instructions: 'When triggered, generate a complete onboarding checklist as individual cards: Day 1 setup, tool access requests, team intro meetings, training schedule, culture doc review, first project assignment, 30-day check-in, 60-day review, 90-day goals.',
    usageCount: 987,
  },
  {
    slug: 'personal-crm',
    name: 'Personal CRM',
    tagline: 'Track relationships and follow-up reminders',
    description: 'Turns your channel into a lightweight CRM. Creates contact cards with context from your notes, suggests follow-up timing based on relationship strength, and generates reminders when it\'s been too long since your last interaction.',
    category: 'Personal',
    tags: ['crm', 'contacts', 'networking', 'follow-up'],
    icon: '🤝',
    action: 'generate',
    instructions: 'Monitor contact cards in the channel. When a card hasn\'t been updated in the timeframe matching its priority (VIP: 2 weeks, Regular: 1 month, Casual: 3 months), generate a follow-up reminder card with context from previous interactions and suggested talking points.',
    usageCount: 1345,
  },
  {
    slug: 'meeting-notes',
    name: 'Meeting Notes',
    tagline: 'Structure raw meeting notes into action items',
    description: 'Takes raw, unstructured meeting notes and transforms them into organized cards. Extracts action items, decisions made, key discussion points, and follow-ups. Each action item becomes its own card assigned to the relevant column.',
    category: 'Productivity',
    tags: ['meetings', 'notes', 'actions', 'organization'],
    icon: '📋',
    action: 'generate',
    instructions: 'When a card with meeting notes is added to Inbox, parse the content. Extract: key decisions (add to a summary card), action items (create individual cards with owners if mentioned), and open questions (create cards in a Questions column). Link all generated cards back to the original notes.',
    usageCount: 2789,
  },
  {
    slug: 'habit-tracker',
    name: 'Habit Tracker',
    tagline: 'Daily habit cards with streak tracking',
    description: 'Generates daily habit check-in cards based on your configured habits. Tracks streaks, celebrates milestones, and gently nudges when habits are missed. Visual progress through card movements between "To Do" and "Done" columns.',
    category: 'Personal',
    tags: ['habits', 'daily', 'streaks', 'wellness'],
    icon: '✨',
    action: 'generate',
    instructions: 'Each morning, generate a daily habits card listing all configured habits as checkboxes. Track consecutive days completed. At 7, 30, and 100 day streaks, add a celebration note. If a habit is missed for 2+ days, generate a gentle nudge card with motivation.',
    usageCount: 1876,
  },
  {
    slug: 'goal-setting',
    name: 'Goal Architect',
    tagline: 'Break ambitious goals into actionable milestones',
    description: 'Takes a high-level goal and breaks it down into quarterly milestones, monthly targets, and weekly actionable tasks. Creates a card hierarchy that makes overwhelming goals feel manageable. Reviews and adjusts based on actual progress.',
    category: 'Personal',
    tags: ['goals', 'planning', 'milestones', 'okr'],
    icon: '🏔️',
    action: 'generate',
    instructions: 'When a goal card is added, analyze it and generate a breakdown: 1 card per quarterly milestone, each with monthly targets. Generate this week\'s actionable tasks as separate cards. Every week, review progress and suggest adjustments to the timeline.',
    usageCount: 2234,
  },
  {
    slug: 'book-tracker',
    name: 'Book Tracker',
    tagline: 'Track reading with notes and key takeaways',
    description: 'Manage your reading list as a Kanban flow. When you finish a book, generates a summary card with key takeaways, memorable quotes, and how it connects to other books you\'ve read. Suggests next reads based on your patterns.',
    category: 'Personal',
    tags: ['books', 'reading', 'notes', 'learning'],
    icon: '📚',
    action: 'generate',
    instructions: 'Track books through columns: Want to Read → Reading → Finished. When a book card moves to Finished, generate a summary card with: 3 key takeaways, 2 memorable quotes, a one-paragraph review, and 2 suggested next reads based on themes.',
    usageCount: 1654,
  },
  {
    slug: 'feedback-collector',
    name: 'Feedback Collector',
    tagline: 'Aggregate and theme user feedback automatically',
    description: 'Collects scattered user feedback from various sources and organizes it into themed clusters. Identifies patterns, sentiment trends, and surfaces the most impactful feedback. Generates insight cards that connect individual feedback to product themes.',
    category: 'Engineering',
    tags: ['feedback', 'users', 'product', 'insights'],
    icon: '💬',
    action: 'generate',
    instructions: 'Analyze all feedback cards in the channel. Group by theme (UX, performance, features, bugs). For each theme with 3+ pieces of feedback, generate an insight card summarizing the pattern, affected user count, and suggested product response.',
    usageCount: 1432,
  },
  {
    slug: 'expense-tracker',
    name: 'Expense Tracker',
    tagline: 'Categorize expenses and flag anomalies',
    description: 'Turns expense entries into organized cards categorized by type. Tracks spending against budgets, generates weekly summaries, and flags unusual expenses. Simple card-based expense management without a spreadsheet.',
    category: 'Personal',
    tags: ['expenses', 'budget', 'finance', 'tracking'],
    icon: '💰',
    action: 'modify',
    instructions: 'When an expense card is added, auto-categorize it (food, transport, subscriptions, entertainment, etc.) and add the category tag. Weekly, generate a summary card with total spend by category and comparison to the previous week. Flag any expense that\'s 2x above the category average.',
    usageCount: 876,
  },
  {
    slug: 'roadmap-planner',
    name: 'Roadmap Planner',
    tagline: 'Turn ideas into a sequenced product roadmap',
    description: 'Takes feature ideas and customer requests from your Inbox and organizes them into a sequenced roadmap. Considers dependencies, effort estimates, and impact to suggest optimal ordering. Generates quarterly roadmap overview cards.',
    category: 'Engineering',
    tags: ['roadmap', 'product', 'planning', 'features'],
    icon: '🗺️',
    action: 'move',
    instructions: 'Analyze cards in the Ideas column. Score each by estimated impact (1-5) and effort (1-5). Prioritize high-impact, low-effort items first. Generate a quarterly roadmap card showing the suggested sequence. Move top items to the "Next Up" column.',
    usageCount: 1789,
  },
  {
    slug: 'launch-checklist',
    name: 'Product Launch',
    tagline: 'Complete launch checklist from announcement to follow-up',
    description: 'Generates a comprehensive product launch checklist covering pre-launch prep, launch day tasks, and post-launch follow-up. Includes marketing, engineering, support, and analytics tasks. Each item becomes a trackable card.',
    category: 'Marketing',
    tags: ['launch', 'checklist', 'product', 'go-to-market'],
    icon: '🚀',
    action: 'generate',
    instructions: 'Generate a complete launch checklist as individual cards: Pre-launch (landing page, email sequence, social assets, press kit, beta testing), Launch Day (deploy, announce, monitor, support), Post-Launch (analytics review, user feedback, iteration plan, case study).',
    usageCount: 1234,
  },
  {
    slug: 'brainstorm-board',
    name: 'Brainstorm Board',
    tagline: 'AI-facilitated brainstorming with idea expansion',
    description: 'Supercharges brainstorming sessions. When you add a seed idea, generates 5 related variations, counter-perspectives, and "what if" expansions. Groups related ideas together and identifies the most promising directions based on novelty and feasibility.',
    category: 'Creative',
    tags: ['brainstorm', 'ideas', 'creative', 'innovation'],
    icon: '💡',
    action: 'generate',
    instructions: 'When a new idea card appears in Inbox, generate 5 expansion cards: 2 variations on the idea, 1 opposite/contrarian take, 1 "what if we 10x this" version, and 1 simplified MVP version. Add a connections card showing how this relates to existing ideas.',
    usageCount: 2567,
  },
  {
    slug: 'okr-tracker',
    name: 'OKR Tracker',
    tagline: 'Track objectives and key results with auto-scoring',
    description: 'Manages your OKRs as a Kanban flow. Each objective gets a card with linked key results. Auto-calculates progress scores based on key result completion. Generates weekly check-in cards and quarterly review summaries.',
    category: 'Team',
    tags: ['okr', 'objectives', 'tracking', 'quarterly'],
    icon: '📊',
    action: 'generate',
    instructions: 'Track OKR cards through the quarter. Each objective card should have key results as checklist items with targets. Weekly, generate a check-in card showing progress % for each objective. At quarter end, generate a review card with scores (0.0-1.0) and learnings.',
    usageCount: 1456,
  },
  {
    slug: 'applicant-tracker',
    name: 'Applicant Tracker',
    tagline: 'Lightweight ATS in your Kanban board',
    description: 'Track job applicants through your hiring pipeline. Cards move through Applied → Screening → Interview → Offer → Hired columns. Auto-generates interview prep cards, sends follow-up reminders, and maintains candidate notes.',
    category: 'Team',
    tags: ['hiring', 'ats', 'recruitment', 'candidates'],
    icon: '👥',
    action: 'generate',
    instructions: 'Track candidate cards through the pipeline. When a card moves to Interview, generate an interview prep card with suggested questions based on the role and candidate background. If a card stays in any column for 5+ days, generate a follow-up reminder.',
    usageCount: 678,
  },
  {
    slug: 'support-ticket-manager',
    name: 'Support Tickets',
    tagline: 'Triage and track support requests efficiently',
    description: 'Manages customer support tickets as cards. Auto-categorizes by type (bug, feature request, question, billing), suggests response templates, and escalates based on severity and wait time. Generates daily support health summaries.',
    category: 'Engineering',
    tags: ['support', 'tickets', 'customer', 'helpdesk'],
    icon: '🎫',
    action: 'move',
    instructions: 'Auto-categorize incoming support cards by type and severity. Suggest response templates based on similar past tickets. If a ticket is unresponded for 24h, move to Urgent. Daily, generate a health card: open tickets, avg response time, top categories.',
    usageCount: 1123,
  },
  {
    slug: 'time-tracker',
    name: 'Time Tracker',
    tagline: 'Log time spent and analyze work patterns',
    description: 'Simple time tracking through card movements. Logs when cards enter and leave each column to calculate time spent. Generates weekly time reports showing where your hours went, identifies time sinks, and suggests efficiency improvements.',
    category: 'Productivity',
    tags: ['time', 'tracking', 'productivity', 'reports'],
    icon: '⏱️',
    action: 'generate',
    instructions: 'Track time by monitoring when cards move between columns. Log entry/exit timestamps. Weekly, generate a time report card: total hours by column, longest-running tasks, average cycle time, and comparison to previous week. Flag tasks over 2x average time.',
    usageCount: 1987,
  },
]

export const channels: MarketplaceChannel[] = [
  {
    slug: 'product-team',
    name: 'Product Team',
    tagline: 'Ship features with structured product development',
    description: 'A complete product development workspace. Organized columns track features from ideation through launch. AI helps prioritize the backlog, generates user stories, and keeps the team aligned on what matters most.',
    category: 'Team',
    tags: ['product', 'features', 'development', 'agile'],
    icon: '🏗️',
    columns: ['Ideas', 'Researching', 'Spec\'d Out', 'Building', 'QA', 'Shipped'],
    aiInstructions: 'Help the product team prioritize features by impact and effort. Generate user stories in standard format. Surface dependencies between cards. Weekly, summarize progress and suggest what to focus on next.',
    usageCount: 3456,
  },
  {
    slug: 'growth-team',
    name: 'Growth Team',
    tagline: 'Experiment-driven growth with hypothesis tracking',
    description: 'Run growth experiments systematically. Each experiment is a card with a hypothesis, metric to track, and expected outcome. AI suggests experiments based on your product and tracks results across the pipeline.',
    category: 'Team',
    tags: ['growth', 'experiments', 'metrics', 'marketing'],
    icon: '📈',
    columns: ['Hypotheses', 'Designing', 'Running', 'Analyzing', 'Wins', 'Learnings'],
    aiInstructions: 'Help the growth team formulate testable hypotheses. Each experiment card should have: hypothesis, primary metric, success criteria, and timeline. After experiments, generate analysis cards summarizing results and next steps.',
    usageCount: 1876,
  },
  {
    slug: 'design-team',
    name: 'Design Team',
    tagline: 'Design workflow from research to handoff',
    description: 'End-to-end design workflow managing projects from user research through final handoff. AI assists with design critique, generates accessibility checklists, and tracks design system consistency across projects.',
    category: 'Team',
    tags: ['design', 'ux', 'ui', 'research'],
    icon: '🎨',
    columns: ['Research', 'Wireframes', 'Visual Design', 'Feedback', 'Polishing', 'Handoff'],
    aiInstructions: 'Assist the design team by generating design review checklists, accessibility audit cards, and design system consistency checks. When a card moves to Feedback, suggest specific areas to evaluate.',
    usageCount: 2134,
  },
  {
    slug: 'makerspace',
    name: 'Makerspace',
    tagline: 'Build things in public with structured accountability',
    description: 'A maker-friendly channel for tracking personal projects. Each project gets cards for milestones, blockers, and shipping goals. AI generates build logs, suggests next steps, and celebrates when you ship.',
    category: 'Creative',
    tags: ['maker', 'projects', 'building', 'indie'],
    icon: '🔨',
    columns: ['Project Ideas', 'Building', 'Blocked', 'Testing', 'Shipped', 'Celebrating'],
    aiInstructions: 'Encourage makers to ship. Break big project ideas into small, shippable milestones. Generate weekly build log summaries. When a card moves to Shipped, create a celebration card highlighting the achievement.',
    usageCount: 1567,
  },
  {
    slug: 'book-club',
    name: 'Book Club',
    tagline: 'Collaborative reading with AI-generated discussion guides',
    description: 'Run a book club where each book is a card journey from nomination to discussion. AI generates chapter discussion questions, key themes analysis, and connects ideas across books the club has read.',
    category: 'Community',
    tags: ['books', 'reading', 'discussion', 'community'],
    icon: '📖',
    columns: ['Nominations', 'Voting', 'Currently Reading', 'Discussion', 'Archive'],
    aiInstructions: 'For each book in Currently Reading, generate weekly discussion questions based on the chapters being covered. Create theme cards connecting ideas to previously read books. Summarize key takeaways after discussion.',
    usageCount: 1234,
  },
  {
    slug: 'feedback-zone',
    name: 'Feedback Zone',
    tagline: 'Structured feedback collection and pattern recognition',
    description: 'Centralize all product feedback in one channel. AI auto-categorizes, identifies patterns, and generates insight summaries. Feedback flows from raw input through analysis to actionable product decisions.',
    category: 'Operations',
    tags: ['feedback', 'product', 'insights', 'users'],
    icon: '📬',
    columns: ['Raw Feedback', 'Categorized', 'Patterns', 'Insights', 'Actions Taken'],
    aiInstructions: 'Auto-categorize incoming feedback by theme (UX, performance, pricing, features). When 3+ pieces of feedback share a theme, generate a pattern card. Periodically create insight summary cards connecting patterns to product opportunities.',
    usageCount: 1890,
  },
  {
    slug: 'early-adopters',
    name: 'Early Adopters',
    tagline: 'Manage your beta community and feedback loop',
    description: 'Track your early adopter program. Manage beta invites, track feature requests from power users, and maintain a changelog that keeps your most engaged users in the loop. AI helps prioritize based on user engagement.',
    category: 'Community',
    tags: ['beta', 'early-adopters', 'community', 'feedback'],
    icon: '🌱',
    columns: ['Invited', 'Active', 'Feature Requests', 'In Progress', 'Shipped to Beta'],
    aiInstructions: 'Help manage the early adopter community. Track engagement levels, surface the most requested features, and generate changelog cards when features ship. Prioritize requests from the most active users.',
    usageCount: 876,
  },
  {
    slug: 'remote-work-tribe',
    name: 'Remote Work Tribe',
    tagline: 'Async-first rituals for distributed teams',
    description: 'Build team culture in a remote-first environment. Structured rituals like async standups, virtual coffee chats, team wins celebrations, and culture moments. AI facilitates connection across time zones.',
    category: 'Team',
    tags: ['remote', 'async', 'culture', 'team-building'],
    icon: '🌍',
    columns: ['Standups', 'Coffee Chats', 'Team Wins', 'Culture', 'Fun Stuff'],
    aiInstructions: 'Generate daily async standup prompts, weekly team win celebrations, and monthly culture moment cards. Suggest coffee chat pairings. Keep things fun and human even in async format.',
    usageCount: 1345,
  },
  {
    slug: 'kanthink-support',
    name: 'Kanthink Support',
    tagline: 'Get help using Kanthink effectively',
    description: 'Official help channel for Kanthink. Contains guides, tips, and best practices for getting the most out of your boards, shrooms, and AI features. AI answers questions and suggests workflows based on your use case.',
    category: 'Community',
    tags: ['help', 'support', 'kanthink', 'guides'],
    icon: '🍄',
    columns: ['Questions', 'Tips & Tricks', 'Guides', 'Feature Requests', 'Resolved'],
    aiInstructions: 'Help users get the most out of Kanthink. Answer questions about features, suggest workflow optimizations, and create tip cards for common use cases. Be friendly, helpful, and reference specific Kanthink features.',
    usageCount: 4567,
  },
  {
    slug: 'startup-founders',
    name: 'Startup Founders',
    tagline: 'Framework for early-stage startup execution',
    description: 'A structured space for startup founders to track their venture from idea validation through launch. Covers customer discovery, MVP building, fundraising, and go-to-market. AI acts as a startup advisor.',
    category: 'Community',
    tags: ['startup', 'founders', 'business', 'entrepreneurship'],
    icon: '🦄',
    columns: ['Validation', 'Building', 'Customers', 'Fundraising', 'Scaling', 'Milestones'],
    aiInstructions: 'Act as a startup advisor. Help founders break down big goals into testable hypotheses. Generate customer discovery question cards, MVP feature prioritization, and investor prep checklists. Be direct and honest.',
    usageCount: 2345,
  },
  {
    slug: 'writers-room',
    name: 'Writers\' Room',
    tagline: 'Develop stories and articles collaboratively',
    description: 'A creative writing workspace. Track stories, articles, and content pieces from idea to published. AI helps with outlining, suggests plot developments, generates character profiles, and provides editing feedback.',
    category: 'Creative',
    tags: ['writing', 'creative', 'stories', 'content'],
    icon: '✍️',
    columns: ['Seeds', 'Outlining', 'First Draft', 'Editing', 'Final Review', 'Published'],
    aiInstructions: 'Help writers develop their work. When a seed idea is added, suggest 3 possible angles. For outlines, help structure the narrative arc. During editing, provide constructive feedback on clarity, pacing, and voice.',
    usageCount: 1678,
  },
  {
    slug: 'personal-productivity',
    name: 'Personal Productivity',
    tagline: 'Your personal command center for getting things done',
    description: 'A personal productivity system combining GTD, time-boxing, and weekly reviews. AI helps you process your inbox, prioritize tasks, and maintain a healthy work-life balance through structured reflection.',
    category: 'Personal',
    tags: ['productivity', 'gtd', 'personal', 'organization'],
    icon: '⚡',
    columns: ['Inbox', 'Today', 'This Week', 'Waiting On', 'Someday', 'Done'],
    aiInstructions: 'Help with personal productivity. Process inbox items by suggesting the right column. Each Monday, generate a weekly plan card. Each Friday, generate a weekly review card summarizing accomplishments and suggesting next week\'s focus.',
    usageCount: 5678,
  },
  {
    slug: 'tech-news',
    name: 'Tech News',
    tagline: 'Curated tech news with AI-generated analysis',
    description: 'Stay on top of tech trends without the noise. AI curates and summarizes the most relevant tech news, generates analysis cards with implications for your work, and tracks developing stories over time.',
    category: 'Learning',
    tags: ['tech', 'news', 'trends', 'analysis'],
    icon: '📰',
    columns: ['Breaking', 'Trending', 'Analysis', 'Implications', 'Archive'],
    aiInstructions: 'Curate tech news by relevance and impact. For each major story, generate: a summary card (key facts), an analysis card (what it means), and an implications card (how it affects different industries). Track stories that develop over multiple days.',
    usageCount: 3234,
  },
  {
    slug: 'beta-testing',
    name: 'Beta Testing',
    tagline: 'Organize beta programs with structured test cycles',
    description: 'Run beta testing programs systematically. Track test cases, bugs, feedback, and release readiness. AI generates test plans based on feature descriptions and helps triage incoming bug reports.',
    category: 'Operations',
    tags: ['beta', 'testing', 'qa', 'release'],
    icon: '🧪',
    columns: ['Test Cases', 'In Testing', 'Bugs Found', 'Fixed', 'Verified', 'Release Ready'],
    aiInstructions: 'Help manage beta testing. Generate test cases from feature descriptions. When bugs are reported, auto-categorize by severity and area. Track fix verification. Generate release readiness summaries when enough tests pass.',
    usageCount: 987,
  },
  {
    slug: 'wellness-community',
    name: 'Wellness Community',
    tagline: 'Track wellness goals with community support',
    description: 'A supportive space for wellness and self-care. Track fitness, nutrition, mental health, and sleep goals as cards. AI provides gentle encouragement, suggests evidence-based wellness tips, and helps maintain streaks.',
    category: 'Community',
    tags: ['wellness', 'health', 'fitness', 'self-care'],
    icon: '🧘',
    columns: ['Goals', 'Daily Habits', 'This Week', 'Wins', 'Reflections'],
    aiInstructions: 'Support wellness goals with gentle, evidence-based guidance. Generate daily wellness tips, celebrate streak milestones, and create weekly reflection cards. Never be judgmental about missed goals — focus on consistency over perfection.',
    usageCount: 1567,
  },
  {
    slug: 'gtd-practitioners',
    name: 'GTD Practitioners',
    tagline: 'David Allen\'s Getting Things Done methodology',
    description: 'A faithful implementation of GTD using Kanban columns. Capture everything in Inbox, process into actionable categories, and review weekly. AI helps with the processing step — deciding next actions, delegating, and deferring.',
    category: 'Personal',
    tags: ['gtd', 'productivity', 'methodology', 'allen'],
    icon: '📥',
    columns: ['Inbox', 'Next Actions', 'Waiting For', 'Projects', 'Someday/Maybe', 'Reference'],
    aiInstructions: 'Apply GTD methodology. For each inbox item: Is it actionable? If yes, what\'s the next action? Takes <2min → do it now. Can be delegated → Waiting For. Needs multiple steps → create a Project. Not actionable → Reference or Someday/Maybe.',
    usageCount: 2890,
  },
  {
    slug: 'build-in-public',
    name: 'Build In Public',
    tagline: 'Document your journey building in the open',
    description: 'Share your building journey publicly. Track milestones, share learnings, and generate update posts. AI helps craft compelling narratives from your progress, suggests what to share, and generates social posts from your build log.',
    category: 'Creative',
    tags: ['build-in-public', 'indie', 'social', 'transparency'],
    icon: '🏗️',
    columns: ['Building', 'Ready to Share', 'Shared', 'Engagement', 'Milestones'],
    aiInstructions: 'Help builders share their journey. Generate weekly update drafts from card activity. Suggest what milestones are worth sharing. Create social post cards (Twitter/X thread format) from build progress. Celebrate publicly shared milestones.',
    usageCount: 1456,
  },
  {
    slug: 'side-hustlers',
    name: 'Side Hustlers',
    tagline: 'Manage side projects without burning out',
    description: 'Balance side projects with your day job. Track multiple ventures with realistic time budgets. AI helps prioritize across projects, suggests when to double down or pivot, and ensures you\'re making progress without overcommitting.',
    category: 'Personal',
    tags: ['side-hustle', 'projects', 'balance', 'entrepreneurship'],
    icon: '🌙',
    columns: ['Ideas', 'Active Projects', 'This Week', 'On Hold', 'Revenue', 'Retired'],
    aiInstructions: 'Help side hustlers stay focused. Limit active projects to 2-3. Generate weekly time budgets based on available hours. Suggest when a project should be paused or retired. Track revenue milestones and celebrate wins.',
    usageCount: 1789,
  },
  {
    slug: 'daily-gratitude',
    name: 'Daily Gratitude',
    tagline: 'Cultivate gratitude with daily reflections',
    description: 'A mindful space for daily gratitude practice. Each day generates a thoughtful prompt for reflection. AI notices patterns in what you\'re grateful for and surfaces connections you might have missed. Builds a beautiful archive of positive moments.',
    category: 'Personal',
    tags: ['gratitude', 'mindfulness', 'daily', 'reflection'],
    icon: '🙏',
    columns: ['Today', 'This Week', 'Themes', 'Milestones', 'Archive'],
    aiInstructions: 'Generate daily gratitude prompts that go beyond the obvious. Vary between: people, experiences, small moments, growth, and challenges that taught something. Monthly, generate a themes card showing patterns in what brings joy.',
    usageCount: 2345,
  },
  {
    slug: 'jugglers-club',
    name: 'Jugglers Club',
    tagline: 'For people spinning many plates at once',
    description: 'When you\'re juggling multiple responsibilities — work, family, projects, health — this channel helps keep all the balls in the air. AI tracks what needs attention today and warns when something\'s been neglected too long.',
    category: 'Personal',
    tags: ['juggling', 'balance', 'multi-tasking', 'life'],
    icon: '🤹',
    columns: ['Plates Spinning', 'Needs Attention', 'Today\'s Focus', 'Handled', 'Dropped (Pick Up)'],
    aiInstructions: 'Help jugglers maintain balance across life areas. Track when each "plate" was last attended to. If something hasn\'t been touched in its expected cadence, move to Needs Attention. Generate a daily focus card suggesting the 3 most urgent plates.',
    usageCount: 1123,
  },
]

// Helper functions
export function getShroom(slug: string): MarketplaceShroom | undefined {
  return shrooms.find(s => s.slug === slug)
}

export function getChannel(slug: string): MarketplaceChannel | undefined {
  return channels.find(c => c.slug === slug)
}

export function getShroomsByCategory(category: string): MarketplaceShroom[] {
  return shrooms.filter(s => s.category === category)
}

export function getChannelsByCategory(category: string): MarketplaceChannel[] {
  return channels.filter(c => c.category === category)
}
