// Static seed data for the Kanthink Marketplace
//
// Channels only. The shroom catalogue was removed: a shroom is defined by its
// instructions, capabilities and input requirements, and the templates here carried
// none of that — they were prose blobs that pre-dated the model. Shrooms are built by
// talking to Kan instead.

export interface MarketplaceChannel {
  slug: string
  name: string
  tagline: string
  description: string
  category: string
  tags: string[]
  icon: string // emoji
  columns: string[]
  aiInstructions: string
  usageCount: number
}

export const CHANNEL_CATEGORIES = [
  'Team',
  'Community',
  'Personal',
  'Learning',
  'Creative',
  'Operations',
] as const

export const channels: MarketplaceChannel[] = [
  {
    slug: 'product-team',
    name: 'Product Team',
    tagline: 'Ship features with structured product development',
    description: 'A complete product development workspace. Organized columns track features from ideation through launch. AI helps prioritize the backlog, generates user stories, and keeps the team aligned on what matters most.',
    category: 'Team',
    tags: ['product', 'features', 'development', 'agile'],
    icon: '🏗️',
    columns: ['Ideas', 'Researching', 'Spec\'d Out', 'Building', 'QA', 'Shipped'],
    aiInstructions: 'Help the product team prioritize features by impact and effort. Generate user stories in standard format. Surface dependencies between cards. Weekly, summarize progress and suggest what to focus on next.',
    usageCount: 3456,
  },
  {
    slug: 'growth-team',
    name: 'Growth Team',
    tagline: 'Experiment-driven growth with hypothesis tracking',
    description: 'Run growth experiments systematically. Each experiment is a card with a hypothesis, metric to track, and expected outcome. AI suggests experiments based on your product and tracks results across the pipeline.',
    category: 'Team',
    tags: ['growth', 'experiments', 'metrics', 'marketing'],
    icon: '📈',
    columns: ['Hypotheses', 'Designing', 'Running', 'Analyzing', 'Wins', 'Learnings'],
    aiInstructions: 'Help the growth team formulate testable hypotheses. Each experiment card should have: hypothesis, primary metric, success criteria, and timeline. After experiments, generate analysis cards summarizing results and next steps.',
    usageCount: 1876,
  },
  {
    slug: 'design-team',
    name: 'Design Team',
    tagline: 'Design workflow from research to handoff',
    description: 'End-to-end design workflow managing projects from user research through final handoff. AI assists with design critique, generates accessibility checklists, and tracks design system consistency across projects.',
    category: 'Team',
    tags: ['design', 'ux', 'ui', 'research'],
    icon: '🎨',
    columns: ['Research', 'Wireframes', 'Visual Design', 'Feedback', 'Polishing', 'Handoff'],
    aiInstructions: 'Assist the design team by generating design review checklists, accessibility audit cards, and design system consistency checks. When a card moves to Feedback, suggest specific areas to evaluate.',
    usageCount: 2134,
  },
  {
    slug: 'makerspace',
    name: 'Makerspace',
    tagline: 'Build things in public with structured accountability',
    description: 'A maker-friendly channel for tracking personal projects. Each project gets cards for milestones, blockers, and shipping goals. AI generates build logs, suggests next steps, and celebrates when you ship.',
    category: 'Creative',
    tags: ['maker', 'projects', 'building', 'indie'],
    icon: '🔨',
    columns: ['Project Ideas', 'Building', 'Blocked', 'Testing', 'Shipped', 'Celebrating'],
    aiInstructions: 'Encourage makers to ship. Break big project ideas into small, shippable milestones. Generate weekly build log summaries. When a card moves to Shipped, create a celebration card highlighting the achievement.',
    usageCount: 1567,
  },
  {
    slug: 'book-club',
    name: 'Book Club',
    tagline: 'Collaborative reading with AI-generated discussion guides',
    description: 'Run a book club where each book is a card journey from nomination to discussion. AI generates chapter discussion questions, key themes analysis, and connects ideas across books the club has read.',
    category: 'Community',
    tags: ['books', 'reading', 'discussion', 'community'],
    icon: '📖',
    columns: ['Nominations', 'Voting', 'Currently Reading', 'Discussion', 'Archive'],
    aiInstructions: 'For each book in Currently Reading, generate weekly discussion questions based on the chapters being covered. Create theme cards connecting ideas to previously read books. Summarize key takeaways after discussion.',
    usageCount: 1234,
  },
  {
    slug: 'feedback-zone',
    name: 'Feedback Zone',
    tagline: 'Structured feedback collection and pattern recognition',
    description: 'Centralize all product feedback in one channel. AI auto-categorizes, identifies patterns, and generates insight summaries. Feedback flows from raw input through analysis to actionable product decisions.',
    category: 'Operations',
    tags: ['feedback', 'product', 'insights', 'users'],
    icon: '📬',
    columns: ['Raw Feedback', 'Categorized', 'Patterns', 'Insights', 'Actions Taken'],
    aiInstructions: 'Auto-categorize incoming feedback by theme (UX, performance, pricing, features). When 3+ pieces of feedback share a theme, generate a pattern card. Periodically create insight summary cards connecting patterns to product opportunities.',
    usageCount: 1890,
  },
  {
    slug: 'early-adopters',
    name: 'Early Adopters',
    tagline: 'Manage your beta community and feedback loop',
    description: 'Track your early adopter program. Manage beta invites, track feature requests from power users, and maintain a changelog that keeps your most engaged users in the loop. AI helps prioritize based on user engagement.',
    category: 'Community',
    tags: ['beta', 'early-adopters', 'community', 'feedback'],
    icon: '🌱',
    columns: ['Invited', 'Active', 'Feature Requests', 'In Progress', 'Shipped to Beta'],
    aiInstructions: 'Help manage the early adopter community. Track engagement levels, surface the most requested features, and generate changelog cards when features ship. Prioritize requests from the most active users.',
    usageCount: 876,
  },
  {
    slug: 'remote-work-tribe',
    name: 'Remote Work Tribe',
    tagline: 'Async-first rituals for distributed teams',
    description: 'Build team culture in a remote-first environment. Structured rituals like async standups, virtual coffee chats, team wins celebrations, and culture moments. AI facilitates connection across time zones.',
    category: 'Team',
    tags: ['remote', 'async', 'culture', 'team-building'],
    icon: '🌍',
    columns: ['Standups', 'Coffee Chats', 'Team Wins', 'Culture', 'Fun Stuff'],
    aiInstructions: 'Generate daily async standup prompts, weekly team win celebrations, and monthly culture moment cards. Suggest coffee chat pairings. Keep things fun and human even in async format.',
    usageCount: 1345,
  },
  {
    slug: 'kanthink-support',
    name: 'Kanthink Support',
    tagline: 'Get help using Kanthink effectively',
    description: 'Official help channel for Kanthink. Contains guides, tips, and best practices for getting the most out of your boards, shrooms, and AI features. AI answers questions and suggests workflows based on your use case.',
    category: 'Community',
    tags: ['help', 'support', 'kanthink', 'guides'],
    icon: '🍄',
    columns: ['Questions', 'Tips & Tricks', 'Guides', 'Feature Requests', 'Resolved'],
    aiInstructions: 'Help users get the most out of Kanthink. Answer questions about features, suggest workflow optimizations, and create tip cards for common use cases. Be friendly, helpful, and reference specific Kanthink features.',
    usageCount: 4567,
  },
  {
    slug: 'startup-founders',
    name: 'Startup Founders',
    tagline: 'Framework for early-stage startup execution',
    description: 'A structured space for startup founders to track their venture from idea validation through launch. Covers customer discovery, MVP building, fundraising, and go-to-market. AI acts as a startup advisor.',
    category: 'Community',
    tags: ['startup', 'founders', 'business', 'entrepreneurship'],
    icon: '🦄',
    columns: ['Validation', 'Building', 'Customers', 'Fundraising', 'Scaling', 'Milestones'],
    aiInstructions: 'Act as a startup advisor. Help founders break down big goals into testable hypotheses. Generate customer discovery question cards, MVP feature prioritization, and investor prep checklists. Be direct and honest.',
    usageCount: 2345,
  },
  {
    slug: 'writers-room',
    name: 'Writers\' Room',
    tagline: 'Develop stories and articles collaboratively',
    description: 'A creative writing workspace. Track stories, articles, and content pieces from idea to published. AI helps with outlining, suggests plot developments, generates character profiles, and provides editing feedback.',
    category: 'Creative',
    tags: ['writing', 'creative', 'stories', 'content'],
    icon: '✍️',
    columns: ['Seeds', 'Outlining', 'First Draft', 'Editing', 'Final Review', 'Published'],
    aiInstructions: 'Help writers develop their work. When a seed idea is added, suggest 3 possible angles. For outlines, help structure the narrative arc. During editing, provide constructive feedback on clarity, pacing, and voice.',
    usageCount: 1678,
  },
  {
    slug: 'personal-productivity',
    name: 'Personal Productivity',
    tagline: 'Your personal command center for getting things done',
    description: 'A personal productivity system combining GTD, time-boxing, and weekly reviews. AI helps you process your inbox, prioritize tasks, and maintain a healthy work-life balance through structured reflection.',
    category: 'Personal',
    tags: ['productivity', 'gtd', 'personal', 'organization'],
    icon: '⚡',
    columns: ['Inbox', 'Today', 'This Week', 'Waiting On', 'Someday', 'Done'],
    aiInstructions: 'Help with personal productivity. Process inbox items by suggesting the right column. Each Monday, generate a weekly plan card. Each Friday, generate a weekly review card summarizing accomplishments and suggesting next week\'s focus.',
    usageCount: 5678,
  },
  {
    slug: 'tech-news',
    name: 'Tech News',
    tagline: 'Curated tech news with AI-generated analysis',
    description: 'Stay on top of tech trends without the noise. AI curates and summarizes the most relevant tech news, generates analysis cards with implications for your work, and tracks developing stories over time.',
    category: 'Learning',
    tags: ['tech', 'news', 'trends', 'analysis'],
    icon: '📰',
    columns: ['Breaking', 'Trending', 'Analysis', 'Implications', 'Archive'],
    aiInstructions: 'Curate tech news by relevance and impact. For each major story, generate: a summary card (key facts), an analysis card (what it means), and an implications card (how it affects different industries). Track stories that develop over multiple days.',
    usageCount: 3234,
  },
  {
    slug: 'beta-testing',
    name: 'Beta Testing',
    tagline: 'Organize beta programs with structured test cycles',
    description: 'Run beta testing programs systematically. Track test cases, bugs, feedback, and release readiness. AI generates test plans based on feature descriptions and helps triage incoming bug reports.',
    category: 'Operations',
    tags: ['beta', 'testing', 'qa', 'release'],
    icon: '🧪',
    columns: ['Test Cases', 'In Testing', 'Bugs Found', 'Fixed', 'Verified', 'Release Ready'],
    aiInstructions: 'Help manage beta testing. Generate test cases from feature descriptions. When bugs are reported, auto-categorize by severity and area. Track fix verification. Generate release readiness summaries when enough tests pass.',
    usageCount: 987,
  },
  {
    slug: 'wellness-community',
    name: 'Wellness Community',
    tagline: 'Track wellness goals with community support',
    description: 'A supportive space for wellness and self-care. Track fitness, nutrition, mental health, and sleep goals as cards. AI provides gentle encouragement, suggests evidence-based wellness tips, and helps maintain streaks.',
    category: 'Community',
    tags: ['wellness', 'health', 'fitness', 'self-care'],
    icon: '🧘',
    columns: ['Goals', 'Daily Habits', 'This Week', 'Wins', 'Reflections'],
    aiInstructions: 'Support wellness goals with gentle, evidence-based guidance. Generate daily wellness tips, celebrate streak milestones, and create weekly reflection cards. Never be judgmental about missed goals — focus on consistency over perfection.',
    usageCount: 1567,
  },
  {
    slug: 'gtd-practitioners',
    name: 'GTD Practitioners',
    tagline: 'David Allen\'s Getting Things Done methodology',
    description: 'A faithful implementation of GTD using Kanban columns. Capture everything in Inbox, process into actionable categories, and review weekly. AI helps with the processing step — deciding next actions, delegating, and deferring.',
    category: 'Personal',
    tags: ['gtd', 'productivity', 'methodology', 'allen'],
    icon: '📥',
    columns: ['Inbox', 'Next Actions', 'Waiting For', 'Projects', 'Someday/Maybe', 'Reference'],
    aiInstructions: 'Apply GTD methodology. For each inbox item: Is it actionable? If yes, what\'s the next action? Takes <2min → do it now. Can be delegated → Waiting For. Needs multiple steps → create a Project. Not actionable → Reference or Someday/Maybe.',
    usageCount: 2890,
  },
  {
    slug: 'build-in-public',
    name: 'Build In Public',
    tagline: 'Document your journey building in the open',
    description: 'Share your building journey publicly. Track milestones, share learnings, and generate update posts. AI helps craft compelling narratives from your progress, suggests what to share, and generates social posts from your build log.',
    category: 'Creative',
    tags: ['build-in-public', 'indie', 'social', 'transparency'],
    icon: '🏗️',
    columns: ['Building', 'Ready to Share', 'Shared', 'Engagement', 'Milestones'],
    aiInstructions: 'Help builders share their journey. Generate weekly update drafts from card activity. Suggest what milestones are worth sharing. Create social post cards (Twitter/X thread format) from build progress. Celebrate publicly shared milestones.',
    usageCount: 1456,
  },
  {
    slug: 'side-hustlers',
    name: 'Side Hustlers',
    tagline: 'Manage side projects without burning out',
    description: 'Balance side projects with your day job. Track multiple ventures with realistic time budgets. AI helps prioritize across projects, suggests when to double down or pivot, and ensures you\'re making progress without overcommitting.',
    category: 'Personal',
    tags: ['side-hustle', 'projects', 'balance', 'entrepreneurship'],
    icon: '🌙',
    columns: ['Ideas', 'Active Projects', 'This Week', 'On Hold', 'Revenue', 'Retired'],
    aiInstructions: 'Help side hustlers stay focused. Limit active projects to 2-3. Generate weekly time budgets based on available hours. Suggest when a project should be paused or retired. Track revenue milestones and celebrate wins.',
    usageCount: 1789,
  },
  {
    slug: 'daily-gratitude',
    name: 'Daily Gratitude',
    tagline: 'Cultivate gratitude with daily reflections',
    description: 'A mindful space for daily gratitude practice. Each day generates a thoughtful prompt for reflection. AI notices patterns in what you\'re grateful for and surfaces connections you might have missed. Builds a beautiful archive of positive moments.',
    category: 'Personal',
    tags: ['gratitude', 'mindfulness', 'daily', 'reflection'],
    icon: '🙏',
    columns: ['Today', 'This Week', 'Themes', 'Milestones', 'Archive'],
    aiInstructions: 'Generate daily gratitude prompts that go beyond the obvious. Vary between: people, experiences, small moments, growth, and challenges that taught something. Monthly, generate a themes card showing patterns in what brings joy.',
    usageCount: 2345,
  },
  {
    slug: 'jugglers-club',
    name: 'Jugglers Club',
    tagline: 'For people spinning many plates at once',
    description: 'When you\'re juggling multiple responsibilities — work, family, projects, health — this channel helps keep all the balls in the air. AI tracks what needs attention today and warns when something\'s been neglected too long.',
    category: 'Personal',
    tags: ['juggling', 'balance', 'multi-tasking', 'life'],
    icon: '🤹',
    columns: ['Plates Spinning', 'Needs Attention', 'Today\'s Focus', 'Handled', 'Dropped (Pick Up)'],
    aiInstructions: 'Help jugglers maintain balance across life areas. Track when each "plate" was last attended to. If something hasn\'t been touched in its expected cadence, move to Needs Attention. Generate a daily focus card suggesting the 3 most urgent plates.',
    usageCount: 1123,
  },
]


// Helper functions
export function getChannel(slug: string): MarketplaceChannel | undefined {
  return channels.find(c => c.slug === slug)
}

export function getChannelsByCategory(category: string): MarketplaceChannel[] {
  return channels.filter(c => c.category === category)
}
