'use client';

import { useState } from 'react';
import type { Card as CardType, RejectionReason } from '@/lib/types';
import { useStore } from '@/lib/store';
import { REJECTION_REASONS } from '@/lib/constants';
import { CardDetailDrawer } from './CardDetailDrawer';

interface ReviewCardProps {
  card: CardType;
}

/**
 * A shroom-generated card awaiting approval. Each one is decided on its own — there's
 * no batch commit, so a run can be worked through a card at a time.
 *
 * The tile keeps its quick Approve/Reject so a run can be cleared without opening
 * anything. Clicking the body opens the same drawer as any other card, because a
 * two-line preview is not enough to judge a card on — the drawer shows the whole
 * thread and swaps its composer for the same decision.
 */
export function ReviewCard({ card }: ReviewCardProps) {
  const approveReviewCard = useStore((s) => s.approveReviewCard);
  const rejectReviewCard = useStore((s) => s.rejectReviewCard);

  const [isRejecting, setIsRejecting] = useState(false);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [reason, setReason] = useState<RejectionReason | undefined>();
  const [feedback, setFeedback] = useState('');

  const messages = card.messages ?? [];
  const rawContent = messages.length > 0 ? messages[0].content : '';
  const contentPreview = card.summary
    || rawContent.replace(/<[^>]+>/g, '').replace(/[#*_`]/g, '').trim();

  const handleConfirmReject = () => {
    rejectReviewCard(card.id, reason, feedback.trim() || undefined);
  };

  return (
    <div className="rounded-md border border-dashed border-violet-300 dark:border-violet-700/60 bg-violet-50/40 dark:bg-violet-950/20 p-2.5">
      <div className="flex items-start gap-2">
        <span className="mt-0.5 text-sm leading-none flex-shrink-0" title="Generated by a shroom">
          🍄
        </span>
        <div className="min-w-0 flex-1">
          <button
            onClick={() => setIsDrawerOpen(true)}
            className="text-left w-full"
          >
            <h4 className="text-xs font-medium text-neutral-800 dark:text-neutral-200 wrap-anywhere">
              {card.title}
            </h4>
            {contentPreview && (
              <p className="mt-0.5 text-xs text-neutral-500 dark:text-neutral-400 line-clamp-2">
                {contentPreview}
              </p>
            )}
          </button>
        </div>
      </div>

      {!isRejecting ? (
        <div className="mt-2 flex items-center gap-1.5">
          <button
            onClick={() => approveReviewCard(card.id)}
            className="flex-1 text-xs font-medium px-2 py-1 rounded bg-violet-600 text-white hover:bg-violet-700 transition-colors"
          >
            Approve
          </button>
          <button
            onClick={() => setIsRejecting(true)}
            className="flex-1 text-xs font-medium px-2 py-1 rounded text-neutral-600 dark:text-neutral-400 hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors"
          >
            Reject
          </button>
        </div>
      ) : (
        <div className="mt-2">
          <p className="text-[11px] text-neutral-500 dark:text-neutral-400 mb-1.5">
            Why? This teaches the shroom.
          </p>
          <div className="flex flex-wrap gap-1 mb-1.5">
            {REJECTION_REASONS.map(({ key, label }) => (
              <button
                key={key}
                onClick={() => setReason(reason === key ? undefined : key)}
                className={`text-[11px] px-2 py-0.5 rounded-full transition-colors ${
                  reason === key
                    ? 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300 font-medium'
                    : 'bg-neutral-200/70 text-neutral-600 dark:bg-neutral-700 dark:text-neutral-400 hover:bg-neutral-300 dark:hover:bg-neutral-600'
                }`}
              >
                {label}
              </button>
            ))}
          </div>
          <input
            type="text"
            placeholder="Add a note... (optional)"
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            maxLength={200}
            className="w-full text-[11px] px-2 py-1 rounded border border-neutral-200 dark:border-neutral-600 bg-white dark:bg-neutral-800 text-neutral-700 dark:text-neutral-300 placeholder-neutral-400 focus:outline-none focus:ring-1 focus:ring-violet-400"
          />
          <div className="mt-1.5 flex items-center gap-1.5">
            <button
              onClick={handleConfirmReject}
              className="flex-1 text-xs font-medium px-2 py-1 rounded bg-red-600 text-white hover:bg-red-700 transition-colors"
            >
              Reject
            </button>
            <button
              onClick={() => setIsRejecting(false)}
              className="flex-1 text-xs font-medium px-2 py-1 rounded text-neutral-600 dark:text-neutral-400 hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      <CardDetailDrawer
        card={card}
        isOpen={isDrawerOpen}
        onClose={() => setIsDrawerOpen(false)}
      />
    </div>
  );
}
